Changed format check to multi-line and return 1 on failure

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -47,9 +47,18 @@ install:
 script:
   - PYTHONPATH=. pytest tests/pytests -vv
   - python setup.py install # install to use python lib in c code
-  - PR_COMMIT_HASH=$(git rev-parse HEAD)
-  - MERGE_COMMIT_HASH=$(git rev-parse master)
-  - git clang-format $MERGE_COMMIT_HASH $PR_COMMIT_HASH --diff
+  - |
+    PR_COMMIT_HASH=$(git rev-parse HEAD)
+    MERGE_COMMIT_HASH=$(git rev-parse master)
+    FORMATTING_ERRORS=$(git clang-format ${MERGE_COMMIT_HASH} ${PR_COMMIT_HASH} --diff)
+    if [ -z "${FORMATTING_ERRORS}"]; then
+      echo "All modified source code properly formatted!"
+      exit 0
+    else
+      echo "Formatting errors in modified source code!"
+      echo "${FORMATTING_ERRORS}"
+      exit 1
+    fi
   - mkdir -p build
   - cd build
   - cmake -DCOVERAGE=ON ..
